### ISSUE TITLE
Works well!

### ISSUE THREAD

**Issue by myleftshoe** [Norbert515/flutter_list_drag_and_drop#1]
Nice one @Norbert515!!! Just got it working in my project, Easy to use. 

A few minor issues:
1. When an item is picked up (but not yet dragged) near the bottom of the screen the list starts scrolling down automatically - strange if your intention is to move the item up. Similarly at top of screen the list automatically starts to scroll up.

2. When an item selected by long pressing below its vertical midpoint, the blank placeholder item is inserted below the item and the item below is moved underneath the elevated item. 

3. If the items use an inkwell, (in my case I was a ListTile with onTap()), pressing an item starts the inkwell animation but holding the press (to select the item for drag) causes the animation to complete on the item below it in the list.  Not really a big deal for me. I just wrapped the ListTile in a GestureDetector and moved nTap from the ListTile to the GD, now no inkwell animations though :-(.

**Comment by Norbert515** [comment]
1. Should be fixable pretty easily, will do so soon.
2. I noticed that one too, not entirely sure why that happens but I will fix that too.
3. This one is tricky. Because drag&drop is implemented using overlays, the system actually creates a new widget when you start dragging. The animation state would need to somehow be transferred to the dragged item.

**Comment by myleftshoe** [comment]
Hi again @Norbert515 ,
For 3. above, simply adding a key to the itemBuilder fixes it.  
```  
Widget _buildList() {
    return new DragAndDropList(
      suburbs,
      canAccept: (a,b) => true,
      dragElevation: 8.0,
      onDragFinish: (before, after) {
        var suburb = suburbs[before];
        suburbs.removeAt(before);
        suburbs.insert(after, suburb);
      },
      itemBuilder: (BuildContext context, suburb) {
        return new Card(
          key: new Key(suburb), //<-----------------------------------
          child: new ExpansionTile(
            title: new Text(suburb),
            children: items.where((it) => it["City"] == suburb).map((it) => new Text(it["ShortAddress"])).toList(),
            leading: new Icon(Icons.android),
          ),
        );
      },
    );
  }
```

Told you I was new to flutter!
