### ISSUE TITLE
Can you please show an example using Firebase document snapshots?

### ISSUE THREAD

**Issue by GroovinChip** [Norbert515/flutter_list_drag_and_drop#10]
If you could please show an example that uses a List of Firebase document snapshots that come in a stream, that would be really helpful. 

With a regular itemBuilder for a ListView.builder, I can specify the index for the List of snapshots. the itemBuilder property for your draggable list only takes an item.

**Comment by Norbert515** [comment]
You should be able to pass the list of snapshots and then use the ItemBuilder to construct your widgets. Or did I misunderstand your problem?

**Comment by Skquark** [comment]
I'm trying to work out the same puzzle, and I almost got it but still not working 100% right.  Here's the simplified version of what I have passing the StreamBuilder's DocumentSnapshot list to the DragAndDropList builder:

```
new StreamBuilder<QuerySnapshot>(
	stream: selectedActivity.collection("Items").snapshots(),
	builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
	  if (!snapshot.hasData)
		return Container(child: Container(
		  alignment: FractionalOffset.center,
		  padding: const EdgeInsets.symmetric(vertical: 10.0),
		  child: CircularProgressIndicator(
			backgroundColor: Colors.amber.shade600,
		  ),
		));
	  if (snapshot.data.documents.length == 0)
		new Text("Add some questions ...", style: TextStyle(fontSize: 16.0));
	  return Expanded(child: 
	     DragAndDropList<DocumentSnapshot>(
		snapshot.data.documents.toList(),
		canBeDraggedTo: (one, two) => true,
		dragElevation: 6.0,
		tilt: 0.04,
		itemBuilder: (BuildContext context, activityItem) {
		  return new SizedBox(
			child: new Card(
			  child: new ListTile(
				leading: Icon(getIcon((activityItem as DocumentSnapshot).data['type'])),
				title: new Text((activityItem as DocumentSnapshot).data['question']),
				onTap: () {
					print("Tapped " + (activityItem as DocumentSnapshot).documentID);
				},
			  ),
			),
		  );
		},
		onDragFinish: (before, after) {
		  print("Moved item before: $before and after: $after");
		},
	  ));
	}
),
```
However, when I add a new document or make an edit to an existing doc, the list does not update itself automatically.  If I go back then return to the list, the changes do show up when it rebuilds.  Any idea why it's not working dynamically?
I also need to work out the reordering onDragFinish, which might be a bit tricky.  Pretty sure I need to add an int field for 'order' and update the effected indexes when it changes, but I didn't want to start implementing that part until after I got it working right when adding or editing.  Any suggestions?  Thanks.

**Comment by Skquark** [comment]
Alright, good call.  I added **key: new GlobalKey(),** to the DragAndDropList properties and that seems to of done the trick.  Didn't need it in the Card widget for the items, so that's good.  I wouldn't of figured that out on my own, so thanks.
Next step is to index the order and try to update list items after changing the position.  May not be intuitive, but at least there's no issue with the component's functionality.  If anyone wants to help with storing the changed order, I'd be happy for the assist.  If I get it worked out, I'll post the update since I'm sure most people needing a reorderable list in Flutter would be using it with Firestore..

**Comment by myleftshoe** [comment]
btw, you don't have to use a global key, any key that is unique in the list is fine, e.g. an OrderId from your data.

**Comment by myleftshoe** [comment]
I'm doing similar reordering with firestore and react. You can define a sortOrder column in your firebase collection. On dragEnd loop through the items and set the sortOrder to the item's index. Then (still in onDragEnd) write the entire list in batch to your firestore collection (google firestore batch operations). Firestore is nice working like that - it will just update the items where the sortOrder has changed - you can watch the updates being made in realtime in the firestore console.

**Comment by Skquark** [comment]
Cool, it's coming along, but still getting stuck.  I added an order field even though it gets clumsy manually changing the index number when adding and deleting items, but in the onDragFinish, how do I get the new list after reordering so I can iterate though and change the order index?  I figured out how to use WriteBatch batch = firestore.batch(); to queue up the updates, thanks for that, very useful.  Now just need to figure out the procedure to get the new order values.. Kinda fun, but more complicated than expected.  Will be satisfying to see it work.

**Comment by myleftshoe** [comment]
Good! In onDragFinish you must already be doing a removeAt and insert on the list. This is the list. You don´t have to manually maintain an index - just use the list index - ie before you write the list to firestore loop over the list and set the sortOrder to the index, that's all you have to do.

**Comment by Skquark** [comment]
Got it.. It makes sense now, I missed the removeAt/insert in the example but after a little adaptation and tinkering, it came together well.  Here is my updated example code that should help others going down this path:
```
  new StreamBuilder<QuerySnapshot>(
	stream: selectedActivity.collection("Items").orderBy("order").snapshots(),
	builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
	  if (!snapshot.hasData)
		return Container(
		  alignment: FractionalOffset.center,
		  padding: const EdgeInsets.symmetric(vertical: 10.0),
		  child: CircularProgressIndicator(
			backgroundColor: Colors.amber.shade600,
		  ),
		);
	  if (snapshot.data.documents.length == 0)
		return Center(child: 
		  new Text("Add Some Questions ...", style: TextStyle(fontSize: 17.0)));
	  return Expanded(child: 
	   DragAndDropList<DocumentSnapshot>(
		snapshot.data.documents,
		canBeDraggedTo: (one, two) => true,
		dragElevation: 8.0,
		tilt: 0.04,
		key: new Key("DragAndDropper"),
		itemBuilder: (BuildContext context, activityItem) {
		  return new SizedBox(
			child: new Card(
			  child: new ListTile(
				leading: Icon(getIcon((activityItem as DocumentSnapshot).data['type'])),
				title: new Text((activityItem as DocumentSnapshot).data['question']),
				onTap: () {
				  print("Tapped " + (activityItem as DocumentSnapshot).documentID);
				},
			  ),
			),
		  );
		},
		onDragFinish: (before, after) {
		  List<DocumentSnapshot> docList = snapshot.data.documents.toList();
		  DocumentSnapshot docItem = docList[before];
		  docList.removeAt(before);
		  docList.insert(after, docItem);
		  WriteBatch batch = Firestore.instance.batch();
		  for (int i = 0; i < docList.length; i++)
			batch.updateData(docList[i].reference, { 'order': i });
		  batch.commit();
		  print("Moved item before: $before after: $after ");
		},
	  ));
	}),
```
That was fun, nice & simple all things considered.  The only thing I can see to make this package better is to see it animate to the tilt and the items to smoothly slide.  Good stuff though, thanks guys.

**Comment by Skquark** [comment]
Something I should point out, even though this implementation works, after spending time trying to get features of my app working around it, I've come to realize that the list does not refresh when the StreamBuilder updates the snapshot, and the snapshot data documents in the Drag and Drop list are not getting changed.  If I go to another page and come back, it's there, but I'm using dialog boxes to edit the data and other real-time stuff.  This problem is the same when using this for normal lists of objects, changing the values in a setState does not get picked up by the widget.  Thought it was something else wrong in my code, so it took me a while.  Hope it's not a hard fix, maybe have it listen for the parent's Stateful widget to update it's state and rebuild the list then, I don't know for sure.  Anyways, thanks, I can work around the bug for now..
