### ISSUE TITLE
I want to change the listview to wrap and then drag the tags.

### ISSUE THREAD

**Issue by renhaoweixiao** [Norbert515/flutter_list_drag_and_drop#16]
for example in rn ：[https://rationalappdev.com/drag-and-drop-tags-in-react-native-part-2-of-2/](https://rationalappdev.com/drag-and-drop-tags-in-react-native-part-2-of-2/)

**Comment by Norbert515** [comment]
Unfortunately, that's not possible with this code. The Flutter team has also pushed this feature to the framework. Maybe check that out: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/reorderable_list.dart
