### ISSUE TITLE
Long press gesture to button

### ISSUE THREAD

**Issue by JoshTechLee** [Norbert515/flutter_list_drag_and_drop#22]
is it possible to change the long press gesture to a button?

If so, how can I go about implementing this?

**Comment by Norbert515** [comment]
Absolutely. You have to set `providesOwnDraggable` to true. 
Then, instead of using the `final WidgetMaker itemBuilder;` use the `  final WidgetMakerAndDelegate itemBuilderCustom;`. You have to call every method of the delegate with the correct event. The best way to handle this is to wrap your button with a `LongPressDraggableItem` or similar and just forward the events.

**Comment by JoshTechLee** [comment]
I looked in the files and realized the "withCustomDraggableBehavior" covers the first part of what you said.  The second part, I'm just not sure how to "forward the events".

Here's what I have now:

```
return StoreConnector<AppState, ViewModel>(
      converter: (Store<AppState> store) => ViewModel.create(store),
      builder: (BuildContext context, ViewModel model) =>
          DragAndDropList.withCustomDraggableBehavior(
            model.userQueue, // list
            itemBuilderCustom: (BuildContext context, entry) {
              return WidgetAndDelegate(
                SizedBox(
                  //  height: 70.0,
                  child: new Card(
                    child: ListTile(
                      title: Text(entry.title),
                      subtitle: Text(entry.subtitle),
                      leading: entry.imageURL is String
                          ? Image.network(
                              entry.imageURL,
                              height: 50.0,
                            )
                          : null,
                      onTap: null,
                      trailing: IconButton(
                        icon: Icon(Icons.drag_handle), onPressed: null, // Drag button
                      ),
                    ),
                  ),
                ),
                DraggableDelegate(),
              );
            },
            onDragFinish: (before, after) {
              Entry data = model.userQueue[before];
              model.userQueue.removeAt(before);
              model.userQueue.insert(after, data);
              print(model.userQueue);
            },
            canBeDraggedTo: (one, two) => true,
            dragElevation: 8.0,
          ),
    );

```

**Comment by Norbert515** [comment]
Sorry for the late response, Githubs notifications are so subtle ...
Anyways, you have instantiate `DraggableDelegate()` before return `WidgetAndDelegate()...` and then call the according methods on it.

```
var delegate = GraggableDelegate();
return MyDraggable(
    onDragStarted: delegate.onDragStarted
   // For every method in the delegate
);
```
Hope this helped!

**Comment by JoshTechLee** [comment]
Yep, thanks a lot buddy!

**Comment by robinjanke** [comment]
> Absolutely. You have to set `providesOwnDraggable` to true.
> Then, instead of using the `final WidgetMaker itemBuilder;` use the ` final WidgetMakerAndDelegate itemBuilderCustom;`. You have to call every method of the delegate with the correct event. The best way to handle this is to wrap your button with a `LongPressDraggableItem` or similar and just forward the events.

Where do i have to set `providesOwnDraggable` to true?

**Comment by robindijkhof** [comment]
Can we get an example on this?
