### ISSUE TITLE
When I open a dialog from a button on a list item and focus on the Text Input within the dialog. DragAndDropList crashes with this:

### ISSUE THREAD

**Issue by mjaffa-figure** [Norbert515/flutter_list_drag_and_drop#23]
When I open a dialog from a button on a list item and focus on the Text Input within the dialog. DragAndDropList crashes with this:

This has happened in flutter's own UI code before and they have fixed this. 

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Builder(dirty):
flutter: Looking up a deactivated widget's ancestor is unsafe.
flutter: At this point the state of the widget's element tree is no longer stable. To safely refer to a
flutter: widget's ancestor in its dispose() method, save a reference to the ancestor by calling
flutter: inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3233:9)
flutter: #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3242:6)
flutter: #2      Element.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3257:12)
flutter: #3      Theme.of (package:flutter/src/material/theme.dart:127:52)
flutter: #4      showDialog.<anonymous closure> (package:flutter/src/material/dialog.dart:610:37)
flutter: #5      _DialogRoute.buildPage (package:flutter/src/widgets/routes.dart:1446:14)
flutter: #6      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:618:43)
flutter: #7      Builder.build (package:flutter/src/widgets/basic.dart:5682:41)
flutter: #8      StatelessElement.build (package:flutter/src/widgets/framework.dart:3731:28)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3835:5)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4803:14)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #43     ProxyElement.update (package:flutter/src/widgets/framework.dart:3947:5)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2729:15)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3689:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3531:5)
flutter: #47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:662:20)
flutter: #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:223:5)
flutter: #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:994:15)
flutter: #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:934:9)
flutter: #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:846:5)
flutter: #53     _invoke (dart:ui/hooks.dart:139:13)
flutter: #54     _drawFrame (dart:ui/hooks.dart:128:3)

**Comment by Norbert515** [comment]
Does this _only_ happen when using this library?

**Comment by mjaffa-figure** [comment]
Yes this only happens when using this library. I bring up this dialog on other parts of the UI and when the Text Input receives focus the keyboard shows and the UI behind the dialog shifts around and the dialog moves up. I suspect this is what is causing the issues with the DragAndDrop ListView. I will quickly replace the DragAndDrop with just a regular ListView builder and see if it happens on their ListView.

**Comment by mjaffa-figure** [comment]
It happens in the regular ListView builder. Not an issue, here. Will report this to the flutter team.
