### ISSUE TITLE
How can I create multiple columns and then transfer list items from one column to another using your code?

### ISSUE THREAD

**Issue by gsunit** [Norbert515/flutter_list_drag_and_drop#26]
I wanted to build something like this.
![drag_drop_flutter](https://user-images.githubusercontent.com/32139782/49285733-4c8be400-f4be-11e8-9d90-a4200c43456c.gif)

Any ideas how I can modify the existing code to implement something like this. Would be happy to send a PR, just need a start. Thanks! :)

**Comment by Norbert515** [comment]
This one is quite tricky, but _basically_ it's just the same principle in 2D instead of 1D. Though I can imagine it being quite a bit more complicated.
