### ISSUE TITLE
How do I scroll to a specific position ?

### ISSUE THREAD

**Issue by superciccio** [Norbert515/flutter_list_drag_and_drop#27]
In old fashion way ( before using this plugin ) I was doing 

` _scrollController.animateTo(160 * _scrollController.offset,
                  duration: Duration(seconds: 5), curve: Curves.bounceInOut);`

I cannot attach a scroll controller now...

Thanks

**Comment by Norbert515** [comment]
The widget instantiates its own `ScrollController` if you want to provide a custom one, passing it through the constructor shouldn't be a problem.

**Comment by superciccio** [comment]
Hi we can close this issue. ;)
