### ISSUE TITLE
Horizontal scrolling - any news ?

### ISSUE THREAD

**Issue by boeledi** [Norbert515/flutter_list_drag_and_drop#7]
Hi Norbert ,

Your Widget works very well.

Any news for the horizontal Scrolling ?
According to my investigations, a new version of  "drag_target.dart" will soon be made available and will include the notion of axis constraints (see [last merge](https://github.com/DaveShuckerow/flutter/blob/24cb4454f70a7fe9a78af588b127ee52aa200915/packages/flutter/lib/src/widgets/drag_target.dart))

Hope to see your next version soon ...

**Comment by Norbert515** [comment]
To be honest, my implementation is not the best. Back when I wrote this I didn't know the framework well enough to know that I didn't have to use draggables. When I get time I will probably rewrite the library to make it more robust and support many other use cases (including horizontal scrolling).

**Comment by boeledi** [comment]
Hi Norbert,

Many thanks for your answer.
If you want, I just made it work for horizontal lists.

Drop me an email, should you want me to send you the code.

Regards,
